### ISSUE TITLE
CI error 

### ISSUE THREAD

**Issue by dimohamdy** [graphhopper/graphhopper-ios#10]
when try to run in CI greenhouseCI.com this error apper

The following build commands failed:
	ExternalBuildToolExecution graphhopper
(1 failure)

❌  error: You need to run \'make class.list\' first

this message from prepare.mk

	@if [ "$(MAKECMDGOALS)" != "class.list" ]; then echo "error: You need to run \`make class.list\` first";  fi

**Comment by karussell** [comment]
What command did you execute exactly?

**Comment by dimohamdy** [comment]
only try to build version in greenHouseCI this error appear ,it's appear for only once

**Comment by clns** [comment]
@dimohamdy Is this still a problem?

**Comment by dimohamdy** [comment]
no i fix it
