### ISSUE TITLE
Build for armv7s for iphone 5

### ISSUE THREAD

**Issue by ugochirico** [graphhopper/graphhopper-ios#11]
When building my app for armv7s (i.e. iphone 5 device) I got the linker error: 
"file is universal (2 slices) but does not contain a(n) armv7s slice: xxx/build/libgraphhopper.a file 'xxx/build/libgraphhopper.a' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

How can I build the library for armv7s?

**Comment by ugochirico** [comment]
Solved! Simply add in the graphhopper build settings the flag: ARCHS=arm64 armv7s armv7

**Comment by clns** [comment]
:+1:

**Comment by RandyHBH** [comment]
I think this fix should be include in the project. Regards

**Comment by RandyHBH** [comment]
Build for armv7 for iphone 4S, this fix dosn't work, Any help??
This is the error in Xcode
```
ld: 'libs/graphhopper-ios/j2objc/lib/libjre_emul.a(SmallTest.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by RandyHBH** [comment]
I fixt it! Change in my project `Target > Build Settings > Build Options > ENABLE_BITCODE`  from `YES` to `NO`

**Comment by clns** [comment]
Thanks for this info. We'll include it in the project.
