### ISSUE TITLE
Graphhopper cannot find symbol method create(long,XMLStreamReader) iOS

### ISSUE THREAD

**Issue by chathura1** [graphhopper/graphhopper-ios#12]
I used to get latest released graphhopper-ios source:
`git clone --recursive https://github.com/graphhopper/graphhopper-ios.git `
I run to build and import all .jar files to 
`./graphhopper.sh build`

I also get following:
```
 Downloaded: https://repo.maven.apache.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar (2465 KB at 876.0 KB/sec)
 [INFO] 
 [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ graphhopper ---
 [INFO] 
   [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ graphhopper ---
   [INFO] Using 'UTF-8' encoding to copy filtered resources.
   [INFO] Copying 2 resources
   [INFO] Copying 42 resources
   [INFO] 
   [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ graphhopper ---

   [INFO] Changes detected - recompiling the module!
   [INFO] Compiling 206 source files to /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/target/classes
   [INFO] -------------------------------------------------------------
   [ERROR] COMPILATION ERROR : 
   [INFO] -------------------------------------------------------------
   [ERROR] /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/src/main/java/com/graphhopper/reader/OSMInputFile.java:[223,46] error: cannot find symbol
   [ERROR]   symbol:   method create(long,XMLStreamReader)
   location: class OSMNode
   /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/src/main/java/com/graphhopper/reader/OSMInputFile.java:[230,41] error: cannot find symbol
   [ERROR]   symbol:   method create(long,XMLStreamReader)
   location: class OSMWay
   /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/src/main/java/com/graphhopper/reader/OSMInputFile.java:[234,46] error: cannot find symbol
  [INFO] 3 errors 
  [INFO] -------------------------------------------------------------
  [INFO] ------------------------------------------------------------------------
  [INFO] Reactor Summary:
  [INFO] 
  [INFO] GraphHopper Parent Project ......................... SUCCESS [  2.243 s]
  [INFO] GraphHopper Tools LGPL licensed .................... SUCCESS [ 16.804 s]
  [INFO] GraphHopper ........................................ FAILURE [ 15.722 s]
  [INFO] GraphHopper Tools .................................. SKIPPED
  [INFO] ------------------------------------------------------------------------
  [INFO] BUILD FAILURE
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: 35.209 s
  [INFO] Finished at: 2016-02-17T01:07:57-08:00
  [INFO] Final Memory: 13M/133M
  [INFO]   ------------------------------------------------------------------------
  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project graphhopper: Compilation failure: Compilation failure:
  [ERROR] /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/src/main/java/com/graphhopper/reader/OSMInputFile.java:[223,46] error: cannot find symbol
  [ERROR] symbol:   method create(long,XMLStreamReader)
  [ERROR] location: class OSMNode
  [ERROR] /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/src/main/java/com/graphhopper/reader/OSMInputFile.java:[230,41] error: cannot find symbol
  [ERROR] symbol:   method create(long,XMLStreamReader)
  [ERROR] location: class OSMWay
  [ERROR] /Users/myuser/Desktop/graphhopper/graphhopper-ios/graphhopper/core/src/main/java/com/graphhopper/reader/OSMInputFile.java:[234,46] error: cannot find symbol
  [ERROR] -> [Help 1]
  [ERROR] 
```

I also noticed  graphhopper/pom.xml and  graphhopper/web/pom.xml has "<<<<<<< HEAD" text error in line 9.

Can someone make sure the graphhopper-ios and graphhopper-ios-sample are working projects?

**Comment by clns** [comment]
`./graphhopper.sh build` should not be used with this project. The reason is there is some [removed / commented out code](https://github.com/graphhopper/graphhopper/compare/master...ios-compat) in the GraphHopper sources in order for it to work with j2objc and iOS. For example `XMLStreamReader` is removed.

Instead, you should follow [Usage - Xcode](https://github.com/graphhopper/graphhopper-ios#usage) and to import data see [Import data](https://github.com/graphhopper/graphhopper-ios/tree/master/graphhopper-ios-sample#import-data).

If you look at [import-sample.sh](https://github.com/graphhopper/graphhopper-ios/blob/master/graphhopper-ios-sample/import-sample.sh#L16), it does a `git checkout 0.6.0-RC1` in `./graphhopper` before running `./graphhopper.sh import`, because originally GraphHopper is checked out on `ios-compat`.

**Comment by chathura1** [comment]
I am trying to get the graphhopper-ios-sample from https://github.com/graphhopper/graphhopper-ios/tree/master/graphhopper-ios-sample compiling under ios 9.2 Xcode 7.2.  

Do I need to run in this order:
`./graphhopper.sh import  // import maven .jars`
This command does do any imports. Why is that?

To create the sample romania gh file
`./graphhopper-ios-sample/import-sample.sh`

**Comment by clns** [comment]
No, you don't need to run any `graphhopper.sh` commands. The order is:

1. clone the repository

    ```
    git clone --recursive https://github.com/graphhopper/graphhopper-ios.git
    cd graphhopper-ios
    ```

2. do the steps in [Usage - Xcode](https://github.com/graphhopper/graphhopper-ios#usage)
3. import data by following instructions [in the sample app](https://github.com/graphhopper/graphhopper-ios/tree/master/graphhopper-ios-sample#import-data)

    ```
    ./graphhopper-ios-sample/import-sample.sh
    
    # or
    FILE=germany-latest.osm.pbf JAVA_OPTS="-Xmx4096m -Xms1000m -server" ./graphhopper-ios-sample/import-sample.sh
    # if a large file is imported, JAVA_OPTS may need to be changed
    ```

That's it.

**Comment by chathura1** [comment]
Thank you.  I got it to compile.  How do I make import different country files to standalone zip files with graph-data.osm-gh folder and corresponding osm.pbf?

**Comment by karussell** [comment]
For discussion please use our forum: https://discuss.graphhopper.com/
