### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by artiy** [graphhopper/graphhopper-ios#15]
I am trying to run graphhopper sample project on my m/c. I downloaded sample project and followed each and every step as directed in elow link

https://github.com/graphhopper/graphhopper-ios#usage 

and then followed to resolve some shell script issues

https://github.com/graphhopper/graphhopper-ios/issues/12

but still I am getting following issues

ld: warning: -L path '/Users/xeliumtech/Documents/ArtiProjects/graphhopper-ios/build/libgraphhopper.a' is not a directory
ld: library not found for -lgraphhopper
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Need help. I am also attaching my projct structure 

![screen shot 2017-04-04 at 12 56 34 pm](https://cloud.githubusercontent.com/assets/5718195/24645557/3a70aa5e-1936-11e7-8247-35e6bdda4352.png)

**Comment by clns** [comment]
Have you followed the steps from here? https://github.com/graphhopper/graphhopper-ios/issues/12#issuecomment-185574427
I suggest you start from scratch and follow the steps described in the link.

**Comment by artiy** [comment]
Well I did follow each and every step if you say then I can try this again.

**Comment by artiy** [comment]
Hi @clns I did follow all steps again. I am not getting any issue while building the graphhopper.xcodeproj. But when I am trying to build my own project then I am getting following issue

ld: library not found for -ljre_emul
clang: error: linker command failed with exit code 1 (use -v to see invocation)

If you can say anything about then it would be really helpful.

**Comment by clns** [comment]
I haven't seen this error, but you could try building it manually from the Terminal by running this commands in the root of graphhopper-ios:

```sh
make cleanall
make class.list
make
```

If successful, you should see the graphhopper library at `graphhopper-ios/build/libgraphhopper.a` and the header files at `graphhopper-ios/src`. If this doesn't succeed, you could paste the output here to have a look.

If this succeeds, do a Project -> Clean in Xcode and try building again.

**Comment by artiy** [comment]
I am using Xcode 8.2.1. Will this make any difference?

**Comment by clns** [comment]
Should be ok.

**Comment by artiy** [comment]
Need help. Cannot resolve it now also. 

Build it manually from the Terminal by running this commands in the root of graphhopper-ios:

make cleanall
make class.list
make

It was successful, then I did see graphhopper library at graphhopper-ios/build/libgraphhopper.a and the header files at graphhopper-ios/src. 

then i did Project -> Clean in Xcode and try building again.

I am getting following error
ld: library not found for -ljre_emul
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by artiy** [comment]
Update:

Manual build did help me. Right now I mistakenly added ljre_emul in my Linked Frameworks by Libraries. After I deleted it and did manual build everything worked out. Thanks for your response @clns
