### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by artiy** [graphhopper/graphhopper-ios#17]
In continuation of #15. I did solve that problem by removing -ljre_emul and -lgraphhopper files from Linked libraries. If I remove these references my project is building without any issues. In this case I am not using graphhopper-ios-sample. I have created my own project and then followed all steps as directed in the   
https://github.com/graphhopper/graphhopper-ios

Then I tried copying ViewController.h and ViewController.m file code in my project. For that I added all required files and references. I also added Directions.h and Directions.m file. If I remove these files then my builds and I can run it in my xcode 8.2.1 version. Which loads the map but didn't zoom in to any area. On long press I am not able to drop any start and end pin. If I add these files then I am getting following errors

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GHRequest", referenced from:
      objc-class-ref in Directions.o
  "_OBJC_CLASS_$_EncodingManager", referenced from:
      objc-class-ref in Directions.o
  "_OBJC_CLASS_$_GraphHopper", referenced from:
      objc-class-ref in Directions.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So I added  -ljre_emul and -lgraphhopper in linked libraries which is gicing me following error

ld: library not found for -lgraphhopper
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and someimes

ld: library not found for -ljre_emul
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

Please help.

**Comment by artiy** [comment]
I was not running make command which creates lingraphhopper.a file. After that all isues have been resolved.

**Comment by eDickC** [comment]
Hi @artiy, how did you finally solve it? I tried everything what i found in issues, but I always had the same error:

ld: library not found for -ljre_emul
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have swift project and i am really desperate, thanks for any help
