### ISSUE TITLE
Error in Getting Started

### ISSUE THREAD

**Issue by kuchmiyalex** [graphhopper/graphhopper-ios#23]
$ git clone --recursive https://github.com/graphhopper/graphhopper-ios.git
Cloning into 'graphhopper-ios'...
remote: Counting objects: 1923, done.
remote: Total 1923 (delta 0), reused 0 (delta 0), pack-reused 1923
Receiving objects: 100% (1923/1923), 16.34 MiB | 1.75 MiB/s, done.
Resolving deltas: 100% (1141/1141), done.

**fatal: No url found for submodule path 'dependencies/hppc' in .gitmodules**

**Comment by clns** [comment]
Sorry for this, we are in the process of updating the iOS port to GraphHopper 0.9, but we hit some problems so you should use the previous 0.8.2 version. See this comment: https://github.com/graphhopper/graphhopper-ios/issues/20#issuecomment-315815128

**Comment by kuchmiyalex** [comment]
Thanks, solved that.
