### ISSUE TITLE
Error cloning the project

### ISSUE THREAD

**Issue by RandyHBH** [graphhopper/graphhopper-ios#25]
when cloning the project give me this error
`fatal: no submodule mapping found in .gitmodules for path 'dependencies/hppc`
any tip?

**Comment by clns** [comment]
See https://github.com/graphhopper/graphhopper-ios/issues/23

**Comment by RandyHBH** [comment]
Thanks, it will be nice to add that description until the 0.9.0 version is out. thanks for the help
