### ISSUE TITLE
Use graphhopper in exiting project

### ISSUE THREAD

**Issue by cojalvo** [graphhopper/graphhopper-ios#30]
Hi,  i'm try to use graphhopper for ios in existing prject.
i follow the instruction how to use it in Xcode but when im drag&drop the Translations and Libraries groups Xcoode is crashing.

Any idea how to solve it? 
i also try to create the lib by build it separately (it build successfully) and drug the lib to my project, Xcode didn't crush, but i couldn't use the lib. it doesn't recognise it when i try to add `GraphHopper.h` to my bridge file (i'm using swift)

Any idea?

Thanks

**Comment by karussell** [comment]
Would you mind to create a new topic on our forum?

**Comment by cojalvo** [comment]
sure
