### ISSUE TITLE
Rebased to graphhopper master and current ios 

### ISSUE THREAD

**Issue by OlafFlebbeBosch** [graphhopper/graphhopper-ios#46]
Hi, I was working on updating the IOS integration to master. I managed to compile and run and plan a route on a quite recent version of graphhopper.  

In order to minimize the porting changes I rebased my efforts to graphhopper "master" and  made good progress until I hit a blocker.

My repos are https://github.com/oflebbe/graphhopper-ios  and https://github.com/oflebbe/graphhopper (branch ios_compat_new) . The patch to graphhopper is really minimalistic right now.

graphhopper-ios is rather large, since I had to upgrade dependencies.

The code compiles, links, runs ... and dies at route planning with the message
> [java.lang.IllegalArgumentException: You need to specify a profile to perform a routing request, see #1958]
I do not understand what exactly needs to be done, since the tests are rather convoluted at that point and not easily adopted to IOS.

Question 1) I doublechecked with the current Android app and it does not create a ProfileConfig as well.( Does this code really work on Android ?) What would be the correct Java Code to add to Graphhopper initialization or to GHRequest , to fit the default-example.yaml from graphhopper ? (Do I need to add ProfileConfig for CH and LM as well ?) what would be the names ? 

This is one obstacle to be solved for submitting a PR to merge it to graphhopper-ios, if you like to merge it : 
Question 2) What are the prerequistes for merging , if you care ?

**Comment by easbar** [comment]
Thanks for trying to update the ios stuff!

> 1) I doublechecked with the current Android app and it does not create a ProfileConfig as well.( Does this code really work on Android ?) 

Probably not, the profile stuff was only added very recently to the (unreleased) 1.0 version. 

> What would be the correct Java Code to add to Graphhopper initialization or to GHRequest , to fit the default-example.yaml from graphhopper ? (Do I need to add ProfileConfig for CH and LM as well ?) what would be the names ?

What has changed is that when calling `GraphHopper#route(GHRequest)`, `GHRequest` needs to specify a profile (instead of `vehicle/weighting` as it did in the past). This is as easy as setting `ghRequest.setProfile("profileName");`. The profile name is more or less arbitrary (it just cannot use some special characters etc.), but has to match whatever is setup in the config. So to stick with `config-example.yml` it would be `"car"`:

```yaml
profiles:
    - name: car
      vehicle: car
      weighting: fastest
```

> Do I need to add ProfileConfig for CH and LM as well ?) what would be the names ?

Yes if you want to prepare and/or use CH/LM you need to add some corresponding entries to the configuration, for example for the above profile you would do:

```yaml
 profiles_ch:
    - profile: car
 profiles_lm:
    - profile: car
```

Where the `profile` field is just the name of the profile you want to generate the CH/LM preparations for.

> Question 2) What are the prerequistes for merging , if you care ?

Probably not too many prerequisites here as hardly anyone is working on the ios stuff as far as I know.

**Comment by boldtrn** [comment]
Thanks for your work :+1:.

> So to stick with config-example.yml it would be "car"

As far as I understand it, the ios version runs the import using the standard GraphHopper and then loads the Graph on ios. So both the config to import and the config to load the graph should be similar. By default, the import should pick up the default GraphHopper config, which would use car.

So on ios, the same values should be applied as well.

> Question 2) What are the prerequistes for merging , if you care ?

I have seen that there were changes in two classes of the GraphHopper core. [The changes in the helper](https://github.com/oflebbe/graphhopper/commit/28c773b008b152b91b52df553654608ee2af5065#diff-4e518ca1e483cdb8f16fea150c2fb150R166) seems to be very runtime specific. So there was probably an issue with j2objc. Not sure if we can tell j2objc to build these differently or if we could do a check in the java implementation if the runtime is a JRE and only then execute JRE specific code? 

There was a change regarding the [ElevationProvider](https://github.com/oflebbe/graphhopper/commit/28c773b008b152b91b52df553654608ee2af5065#diff-59d362881b641ff1b933a3785503c20eR530). Could you explain why this change was necessary? Does the ElevationProvider uses any JRE specific code or a feature that is unsupported by j2objc?

**Comment by oflebbe** [comment]
@boldtrn The Elevation Classes use java.awt.*  . These classes are simply not supported by j2objc. There is absolutly no way to support AWT with j2objc . However it would be possible to support elevationproviders if we switch to a java-only version (first hit in google was https://github.com/ngageoint/tiff-java , exactly for the same usecase :) )

**Comment by oflebbe** [comment]
@easbar , I had the impression that request.setProfile("car") did not work  error message was "Profile not found" . Ok, have to debug it.

**Comment by easbar** [comment]
> @easbar , I had the impression that request.setProfile("car") did not work error message was "Profile not found" . Ok, have to debug it.

Ok, do you import the graph on another machine and then load it on iOS like @boldtrn said? If yes you have to make sure you are using the same configuration. Do you read `config.yml` again on the iOS side? If not make sure that the profiles are added to the `GraphHopper` class via `GraphHopper#setProfiles` or `GraphHopper#init(GraphHopperConfig)`.

**Comment by oflebbe** [comment]
AFAIK there is no yaml file to be read in Mobile. (Even in android, though I only did a quick glance at the code)
And yes, created the files on a bigger iron and included it in the Mobile App.

**Comment by easbar** [comment]
Then I assume there is a call to `GraphHopper#init(GraphHopperConfig)` and you need to add the profiles (and CH/LM configurations) to `GraphHopperConfig`. The structure in the yaml file should be the same as in `GraphHopperConfig`.

**Comment by karussell** [comment]
> I managed to compile and run and plan a route on a quite recent version of graphhopper.

Really nice!

btw: if you have to define the profile in Java code (and not via config) have a look into our tests: https://github.com/graphhopper/graphhopper/blob/master/reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java#L98

> Probably not too many prerequisites here as hardly anyone is working on the ios stuff as far as I know.

Yeah, any contribution that pushes this forward is very appreciated! See also https://github.com/graphhopper/graphhopper/issues/1940

**Comment by boldtrn** [comment]
> These classes are simply not supported by j2objc. There is absolutly no way to support AWT with j2objc

Ah, I see, using AWT is indeed a bit ugly. Thanks for the explanation. On the other hand, not every ElevationProvider uses AWT, the default `noop` provider doesn't do anything, also the `SRTMProvider` and `SkadiProvider` don't use tiff files. Is there only an exception if the class using AWT is constructed or is there a static error, because the class could be used?

The tiff handling is probably not necessary on ios, so if there is only an error if the class is used we should be able to work around it, since the elevation data (like tiff) is only needed during the import.

**Comment by oflebbe** [comment]
@easbar 

so this should work with config-example.yaml ?
```
hopper.setProfiles(
     *     new ProfileConfig("car").setVehicle("car").setWeighting("fastest"))
hopper.getCHPreparationHandler().setCHProfileConfigs(
     *     new CHProfileConfig("car")
     *   )
```

**Comment by easbar** [comment]
Yes **unless** `hopper.init(ghConfig)` is called after this, because that would overwrite the previous setup.

**Comment by oflebbe** [comment]
@boldtrn Right, but if you look carefully the files are dependent on each other. The NOOP elevation handler works for sure and will be compiled (since it is not listed in https://github.com/oflebbe/graphhopper-ios/blob/master/dependencies/class-exclude.grep ) . But let me ask. Why do we need to have an elevation provider at all at routing time on mobile ? Is there  a use case for it ?

**Comment by boldtrn** [comment]
> Why do we need to have an elevation provider at all at routing time on mobile ?

I actually don't think there is the need to have an ElevationProvider for the routing. IIRC it's only used during the import. 

So I think we could only use the ElevationProvider when we actually import?

**Comment by oflebbe** [comment]
@easbar @karussell  It works somehow! I set the Profile in GHRequest and the ProfileConfig in Graphhopper and the CHPreparationConfig for graphhopper
![screen](https://user-images.githubusercontent.com/1179001/79257467-f092e700-7e89-11ea-93d8-1fa73ab6193c.gif)

**Comment by oflebbe** [comment]
I reworked dependencies: hppc and jts releases will be downloaded from github, rather used as git submodule. I just learned that j2objc has special features to rewrite the code while translating. Maybe this resolves the graphhopper patching issue.

**Comment by karussell** [comment]
Really nice, well done :+1: !

**Comment by Zakalicious** [comment]
Great work! Any chance for a working Swift ios-example? Thanks

**Comment by Zakalicious** [comment]
@OlafFlebbeBosch 

Love the progress. Attempting to compile from your fork in XCode 11.3, macos 10.14 I get this far in building the frame work:

finishing deferred symbolic links:
  j2objc-2.5/frameworks/Guava.framework/Guava -> Versions/Current/Guava
  j2objc-2.5/frameworks/Guava.framework/Versions/Current -> A
  j2objc-2.5/frameworks/Guava.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/GuavaAndroid.framework/Versions/Current -> A
  j2objc-2.5/frameworks/GuavaAndroid.framework/GuavaAndroid -> Versions/Current/GuavaAndroid
  j2objc-2.5/frameworks/GuavaAndroid.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/JSR305.framework/Versions/Current -> A
  j2objc-2.5/frameworks/JSR305.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/JSR305.framework/JSR305 -> Versions/Current/JSR305
  j2objc-2.5/frameworks/JavaxInject.framework/Versions/Current -> A
  j2objc-2.5/frameworks/JavaxInject.framework/JavaxInject -> Versions/Current/JavaxInject
  j2objc-2.5/frameworks/JavaxInject.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/Xalan.framework/Resources -> Versions/Current/Resources
  j2objc-2.5/frameworks/Xalan.framework/Versions/Current -> A
  j2objc-2.5/frameworks/Xalan.framework/Xalan -> Versions/Current/Xalan
  j2objc-2.5/frameworks/Xalan.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/ProtobufRuntime.framework/ProtobufRuntime -> Versions/Current/ProtobufRuntime
  j2objc-2.5/frameworks/ProtobufRuntime.framework/Versions/Current -> A
  j2objc-2.5/frameworks/ProtobufRuntime.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/JUnit.framework/JUnit -> Versions/Current/JUnit
  j2objc-2.5/frameworks/JUnit.framework/Versions/Current -> A
  j2objc-2.5/frameworks/JUnit.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/JRE.framework/JRE -> Versions/Current/JRE
  j2objc-2.5/frameworks/JRE.framework/Versions/Current -> A
  j2objc-2.5/frameworks/JRE.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/Mockito.framework/Versions/Current -> A
  j2objc-2.5/frameworks/Mockito.framework/Headers -> Versions/Current/Headers
  j2objc-2.5/frameworks/Mockito.framework/Mockito -> Versions/Current/Mockito
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by oflebbe** [comment]
@Zakalicious I would prefer to create a new issue , since my original request has been resolved. I will open a new one to discuss building
