### ISSUE TITLE
Version of nodes Crash 

### ISSUE THREAD

**Issue by dimohamdy** [graphhopper/graphhopper-ios#6]
I used Data support .4 but i have crash 
 *** Terminating app due to uncaught exception 'JavaLangIllegalStateException', reason: 'Version of nodes unsupported: 3, expected:4'

**Comment by karussell** [comment]
Please use the mailing list for questions. This indicates that you have different (older) graph files on the disc. Make sure you are using the same version for creating and for reading.

**Comment by dimohamdy** [comment]
I use 
git clone --recursive https://github.com/graphhopper/graphhopper-ios.git
 to get graphhopper are this the last version

**Comment by clns** [comment]
Yes, most probably you have older graph files. Are you using the import method from the sample app? Because if you're using that you shouldn't have problems like this.

Please use the [mailing list](https://lists.openstreetmap.org/listinfo/graphhopper) for questions.

**Comment by dimohamdy** [comment]
I use it , that is in sample how i can use it

**Comment by clns** [comment]
What is the exact command you're using to import the data?

**Comment by dimohamdy** [comment]
hopper = [[GraphHopper alloc] init];
 [hopper setCHEnableWithBoolean:YES];
 [hopper setAllowWritesWithBoolean:NO];
 [hopper setMemoryMapped];
 [hopper setEncodingManagerWithEncodingManager:[[EncodingManager alloc] initWithNSString:@"car"]];
 [hopper load__WithNSString:location];

**Comment by clns** [comment]
No, I mean the command you run to import the data, in the command line (Terminal).

**Comment by dimohamdy** [comment]
it's a offline Data

**Comment by clns** [comment]
Did you use this command to import the graph files (from the root of *graphhopper-ios*)?

```sh
$ ./graphhopper-ios-sample/import-sample.sh
```

**Comment by karussell** [comment]
Hi Ahmed, please if you really want help you need to be more descriptive and invest a bit more time and words into this. Otherwise @clns probably won't be able to do much for you
